name: Mend CLI Scan

on:
  workflow_dispatch

jobs:
  mend-cli:
    name: Mend-CLI
    env:
     #SCA
            MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
            MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
            MEND_URL: https://saas.mend.io
            #SAST
            MEND_SAST_SERVER_URL: https://saas.mend.io/sast
            MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
            MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
    runs-on: ubuntu-latest
    steps:
      # Downloading Mend CLI
      - name: Mend CLI
        run: | 
          echo Downloading Mend CLI
          curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          echo Start Mend CLI scan
          ./mend sca
          ./mend sast
